# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 16:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cal', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('types', models.CharField(choices=[('halal', 'Halal'), ('vegan', 'Vegan'), ('vege', 'Vegetarian')], max_length=100)),
                ('rating_counter', models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.FloatField(default=0, editable=False, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)])),
                ('ip_list_rated', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(choices=[('wingold', 'Wingold'), ('kw', 'KW'), ('mon', 'Mon')], max_length=100)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('caterer', models.TextField()),
                ('menuID', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='menuID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Menu'),
        ),
    ]
