# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 23:49
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170601_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cal',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='food',
            name='rating',
            field=models.IntegerField(default=0, editable=False, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='food',
            name='rating_counter',
            field=models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='types',
            field=models.CharField(choices=[('halal', 'Halal'), ('vegan', 'Vegan'), ('vege', 'Vegetarian')], max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='menu',
            name='location',
            field=models.CharField(choices=[('wingold', 'Wingold'), ('kw', 'KW'), ('mon', 'Mon')], max_length=100),
        ),
    ]
